/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

/**
 *
 * @author nicolasmedina
 */
public class Maininterfaz extends javax.swing.JFrame {

    /**
     * Creates new form Maininterfaz
     */
    public Maininterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        juego = new javax.swing.JButton();
        resistencias = new javax.swing.JButton();
        matrices = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        juego.setBackground(new java.awt.Color(102, 102, 102));
        juego.setText("Piedra papel o Tijera");
        juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoActionPerformed(evt);
            }
        });
        getContentPane().add(juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 216, 49));

        resistencias.setBackground(new java.awt.Color(102, 102, 102));
        resistencias.setText("Calculadora de resistencias");
        resistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resistenciasActionPerformed(evt);
            }
        });
        getContentPane().add(resistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 220, 49));

        matrices.setBackground(new java.awt.Color(102, 102, 102));
        matrices.setText("Calculadora de matrices");
        matrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricesActionPerformed(evt);
            }
        });
        getContentPane().add(matrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 216, 49));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/54974hd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricesActionPerformed
        // TODO add your handling code here:
        matrices abrir = new matrices();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_matricesActionPerformed

    private void resistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resistenciasActionPerformed
        // TODO add your handling code here:
        Resistencias abrir= new Resistencias();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_resistenciasActionPerformed

    private void juegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoActionPerformed
        // TODO add your handling code here:
        interfazjuego abrir = new interfazjuego();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_juegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maininterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maininterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maininterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maininterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maininterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton juego;
    private javax.swing.JButton matrices;
    private javax.swing.JButton resistencias;
    // End of variables declaration//GEN-END:variables
}
