/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

/**
 *
 * @author nicolasmedina
 */
public class Resistencias extends javax.swing.JFrame {

    /**
     * Creates new form Resistencias
     */
    String multiplicadora;
    Double contenido;
    Double calculo;
    Double multiplicador;
    public Resistencias() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gris2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        violeta2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        negro2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        verde2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        rojo2 = new javax.swing.JButton();
        cafe2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        amarillo2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        naranja2 = new javax.swing.JButton();
        blanco2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        azul2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        gris1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        violeta1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        negro1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        verde1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        rojo1 = new javax.swing.JButton();
        cafe1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        amarillo1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        naranja1 = new javax.swing.JButton();
        blanco1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        azul1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        gris3 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        violeta3 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        negro3 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        verde3 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        rojo3 = new javax.swing.JButton();
        cafe3 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        amarillo3 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        naranja3 = new javax.swing.JButton();
        blanco3 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        azul3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        doradoto = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        transpato = new javax.swing.JButton();
        plateadoto = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        rojoto = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        cafeto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        banda2 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        banda1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        banda3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tolerancia = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextPane();
        reiniciar = new javax.swing.JButton();
        colorbanda1 = new javax.swing.JButton();
        colorbanda4 = new javax.swing.JButton();
        colorbanda2 = new javax.swing.JButton();
        colorbanda3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gris2.setBackground(new java.awt.Color(102, 102, 102));
        gris2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gris2ActionPerformed(evt);
            }
        });
        getContentPane().add(gris2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 428, 41, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Violeta");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 402, 71, 20));

        violeta2.setBackground(new java.awt.Color(153, 0, 153));
        violeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                violeta2ActionPerformed(evt);
            }
        });
        getContentPane().add(violeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 402, 41, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gris");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 428, 71, 20));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Negro");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 214, 71, 20));

        negro2.setBackground(new java.awt.Color(0, 0, 0));
        negro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negro2ActionPerformed(evt);
            }
        });
        getContentPane().add(negro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 214, 41, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Blanco");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 454, 71, 20));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Naranja");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 294, 71, 20));

        verde2.setBackground(new java.awt.Color(0, 102, 0));
        verde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verde2ActionPerformed(evt);
            }
        });
        getContentPane().add(verde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 348, 41, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cafe");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 240, 71, 20));

        rojo2.setBackground(new java.awt.Color(255, 51, 0));
        rojo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojo2ActionPerformed(evt);
            }
        });
        getContentPane().add(rojo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 267, 41, 20));

        cafe2.setBackground(new java.awt.Color(102, 51, 0));
        cafe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafe2ActionPerformed(evt);
            }
        });
        getContentPane().add(cafe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 240, 41, 20));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Rojo");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 267, 71, 20));

        amarillo2.setBackground(new java.awt.Color(255, 204, 51));
        amarillo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarillo2ActionPerformed(evt);
            }
        });
        getContentPane().add(amarillo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 321, 41, 20));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Azul");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 375, 71, 20));

        naranja2.setBackground(new java.awt.Color(255, 102, 0));
        naranja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naranja2ActionPerformed(evt);
            }
        });
        getContentPane().add(naranja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 294, 41, 20));

        blanco2.setBackground(new java.awt.Color(255, 255, 255));
        blanco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blanco2ActionPerformed(evt);
            }
        });
        getContentPane().add(blanco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 454, 41, 20));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Amarillo");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 321, 71, 20));

        azul2.setBackground(new java.awt.Color(0, 0, 204));
        azul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azul2ActionPerformed(evt);
            }
        });
        getContentPane().add(azul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 375, 41, 20));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Verde");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 348, 71, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Verde");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 344, 71, 20));

        gris1.setBackground(new java.awt.Color(102, 102, 102));
        gris1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gris1ActionPerformed(evt);
            }
        });
        getContentPane().add(gris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 422, 41, 20));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Violeta");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 396, 71, 20));

        violeta1.setBackground(new java.awt.Color(153, 0, 153));
        violeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                violeta1ActionPerformed(evt);
            }
        });
        getContentPane().add(violeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 396, 41, 20));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Gris");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 422, 71, 20));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Negro");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 214, 71, 20));

        negro1.setBackground(new java.awt.Color(0, 0, 0));
        negro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negro1ActionPerformed(evt);
            }
        });
        getContentPane().add(negro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 214, 41, 20));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Blanco");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 448, 71, 20));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Naranja");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 292, 71, 20));

        verde1.setBackground(new java.awt.Color(0, 102, 0));
        verde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verde1ActionPerformed(evt);
            }
        });
        getContentPane().add(verde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 344, 41, 20));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Cafe");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 240, 71, 20));

        rojo1.setBackground(new java.awt.Color(255, 51, 0));
        rojo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojo1ActionPerformed(evt);
            }
        });
        getContentPane().add(rojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 266, 41, 20));

        cafe1.setBackground(new java.awt.Color(102, 51, 0));
        cafe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafe1ActionPerformed(evt);
            }
        });
        getContentPane().add(cafe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 240, 41, 20));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Rojo");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 266, 71, 20));

        amarillo1.setBackground(new java.awt.Color(255, 204, 51));
        amarillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarillo1ActionPerformed(evt);
            }
        });
        getContentPane().add(amarillo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 318, 41, 20));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Azul");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 370, 71, 20));

        naranja1.setBackground(new java.awt.Color(255, 102, 0));
        naranja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naranja1ActionPerformed(evt);
            }
        });
        getContentPane().add(naranja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 292, 41, 20));

        blanco1.setBackground(new java.awt.Color(255, 255, 255));
        blanco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blanco1ActionPerformed(evt);
            }
        });
        getContentPane().add(blanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 448, 41, 20));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Amarillo");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 318, 71, 20));

        azul1.setBackground(new java.awt.Color(0, 0, 204));
        azul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azul1ActionPerformed(evt);
            }
        });
        getContentPane().add(azul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 370, 41, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Banda 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 180, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Banda 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 180, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Banda Multiplicadora");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 180, -1, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Verde");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 344, 71, 20));

        gris3.setBackground(new java.awt.Color(102, 102, 102));
        gris3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gris3ActionPerformed(evt);
            }
        });
        getContentPane().add(gris3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 422, 41, 20));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Violeta");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 396, 71, 20));

        violeta3.setBackground(new java.awt.Color(153, 0, 153));
        violeta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                violeta3ActionPerformed(evt);
            }
        });
        getContentPane().add(violeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 396, 41, 20));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Gris");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 422, 71, 20));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Negro");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 214, 71, 20));

        negro3.setBackground(new java.awt.Color(0, 0, 0));
        negro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negro3ActionPerformed(evt);
            }
        });
        getContentPane().add(negro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 214, 41, 20));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Blanco");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 448, 71, 20));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Naranja");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 292, 71, 20));

        verde3.setBackground(new java.awt.Color(0, 102, 0));
        verde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verde3ActionPerformed(evt);
            }
        });
        getContentPane().add(verde3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 344, 41, 20));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Cafe");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 240, 71, 20));

        rojo3.setBackground(new java.awt.Color(255, 51, 0));
        rojo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojo3ActionPerformed(evt);
            }
        });
        getContentPane().add(rojo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 266, 41, 20));

        cafe3.setBackground(new java.awt.Color(102, 51, 0));
        cafe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafe3ActionPerformed(evt);
            }
        });
        getContentPane().add(cafe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 240, 41, 20));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Rojo");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 266, 71, 20));

        amarillo3.setBackground(new java.awt.Color(255, 204, 51));
        amarillo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarillo3ActionPerformed(evt);
            }
        });
        getContentPane().add(amarillo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 318, 41, 20));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Azul");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 370, 71, 20));

        naranja3.setBackground(new java.awt.Color(255, 102, 0));
        naranja3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naranja3ActionPerformed(evt);
            }
        });
        getContentPane().add(naranja3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 292, 41, 20));

        blanco3.setBackground(new java.awt.Color(255, 255, 255));
        blanco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blanco3ActionPerformed(evt);
            }
        });
        getContentPane().add(blanco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 448, 41, 20));

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Amarillo");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 318, 71, 20));

        azul3.setBackground(new java.awt.Color(0, 0, 204));
        azul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azul3ActionPerformed(evt);
            }
        });
        getContentPane().add(azul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 370, 41, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tolerancia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 180, -1, -1));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Dorado");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 318, 71, 20));

        doradoto.setBackground(new java.awt.Color(204, 203, 25));
        doradoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doradotoActionPerformed(evt);
            }
        });
        getContentPane().add(doradoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 318, 41, 20));

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Plateado");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 344, 71, 20));

        transpato.setBackground(new java.awt.Color(255, 255, 255));
        transpato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transpatoActionPerformed(evt);
            }
        });
        getContentPane().add(transpato, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 370, 41, 20));

        plateadoto.setBackground(new java.awt.Color(204, 204, 204));
        plateadoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateadotoActionPerformed(evt);
            }
        });
        getContentPane().add(plateadoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 344, 41, 20));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Transparente");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, 105, 20));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Rojo");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 266, 71, 20));

        rojoto.setBackground(new java.awt.Color(255, 51, 0));
        rojoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojotoActionPerformed(evt);
            }
        });
        getContentPane().add(rojoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 266, 41, 20));

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Café");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 292, 71, 20));

        cafeto.setBackground(new java.awt.Color(102, 51, 0));
        cafeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafetoActionPerformed(evt);
            }
        });
        getContentPane().add(cafeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 292, 41, 20));

        jScrollPane1.setViewportView(banda2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 182, -1));

        jScrollPane2.setViewportView(banda1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 182, -1));

        jScrollPane3.setViewportView(banda3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 182, -1));

        jScrollPane4.setViewportView(tolerancia);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 182, -1));

        jScrollPane5.setViewportView(resultado);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 525, 221, 113));

        reiniciar.setBackground(new java.awt.Color(102, 102, 102));
        reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 556, 89, 52));
        getContentPane().add(colorbanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 30, 90));
        getContentPane().add(colorbanda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 30, 90));
        getContentPane().add(colorbanda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 30, 70));
        getContentPane().add(colorbanda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 30, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/electric-resistencia-02.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 450, 120));

        calcular.setBackground(new java.awt.Color(102, 102, 102));
        calcular.setForeground(new java.awt.Color(255, 255, 255));
        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 535, 89, 90));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/54974hd.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void azul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azul2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(0,0,204));
        banda2.setText("6");
    }//GEN-LAST:event_azul2ActionPerformed

    private void blanco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blanco2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(255,255,255));
        banda2.setText("9");
    }//GEN-LAST:event_blanco2ActionPerformed

    private void naranja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naranja2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(255,102,0));
        banda2.setText("3");
    }//GEN-LAST:event_naranja2ActionPerformed

    private void amarillo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarillo2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(255,204,51));
        banda2.setText("4");
    }//GEN-LAST:event_amarillo2ActionPerformed

    private void cafe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafe2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(102,51,0));
        banda2.setText("1");
    }//GEN-LAST:event_cafe2ActionPerformed

    private void rojo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojo2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(255,51,0));
        banda2.setText("2");
    }//GEN-LAST:event_rojo2ActionPerformed

    private void azul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azul1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(0,0,204));
        banda1.setText("6");
    }//GEN-LAST:event_azul1ActionPerformed

    private void blanco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blanco1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(255,255,255));
        banda1.setText("9");
    }//GEN-LAST:event_blanco1ActionPerformed

    private void naranja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naranja1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(255,102,0));
        banda1.setText("3");
    }//GEN-LAST:event_naranja1ActionPerformed

    private void amarillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarillo1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(255,204,51));
        banda1.setText("4");
    }//GEN-LAST:event_amarillo1ActionPerformed

    private void cafe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafe1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(102,51,0));
        banda1.setText("1");
    }//GEN-LAST:event_cafe1ActionPerformed

    private void rojo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojo1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(255,51,0));
        banda1.setText("2");
    }//GEN-LAST:event_rojo1ActionPerformed

    private void verde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verde1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(0,102,0));
        banda1.setText("5");
    }//GEN-LAST:event_verde1ActionPerformed

    private void verde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verde2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(0,102,0));
        banda2.setText("5");
    }//GEN-LAST:event_verde2ActionPerformed

    private void negro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negro2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(0,0,0));
        banda2.setText("0");
    }//GEN-LAST:event_negro2ActionPerformed

    private void violeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_violeta2ActionPerformed
        // TODO add your handling code here:
        colorbanda2.setBackground(new java.awt.Color(153,0,153));
        banda2.setText("7");
    }//GEN-LAST:event_violeta2ActionPerformed

    private void gris2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gris2ActionPerformed
        // TODO add your handling code here:
         colorbanda2.setBackground(new java.awt.Color(102,102,102));
         banda2.setText("8");
    }//GEN-LAST:event_gris2ActionPerformed

    private void negro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negro1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(0,0,0));
        banda1.setText("0");
    }//GEN-LAST:event_negro1ActionPerformed

    private void violeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_violeta1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(153,0,153));
        banda1.setText("7");
    }//GEN-LAST:event_violeta1ActionPerformed

    private void gris1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gris1ActionPerformed
        // TODO add your handling code here:
        colorbanda1.setBackground(new java.awt.Color(102,102,102));
        banda1.setText("8");
    }//GEN-LAST:event_gris1ActionPerformed

    private void gris3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gris3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(102,102,102));
        banda3.setText("1x10^8");
        multiplicadora = "100000000";
    }//GEN-LAST:event_gris3ActionPerformed

    private void violeta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_violeta3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(153,0,153));
        banda3.setText("1x10^7");
        multiplicadora = "10000000";
    }//GEN-LAST:event_violeta3ActionPerformed

    private void negro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negro3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(0,0,0));
        banda3.setText("1x10^0");
        multiplicadora = "1";
    }//GEN-LAST:event_negro3ActionPerformed

    private void verde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verde3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(0,102,0));
        banda3.setText("1x10^5");
        multiplicadora = "100000";
    }//GEN-LAST:event_verde3ActionPerformed

    private void rojo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojo3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(255,51,0));
        banda3.setText("1x10^2");
        multiplicadora = "100";
    }//GEN-LAST:event_rojo3ActionPerformed

    private void cafe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafe3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(102,51,0));
        banda3.setText("1x10^1");
        multiplicadora = "10";
    }//GEN-LAST:event_cafe3ActionPerformed

    private void amarillo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarillo3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(255,204,51));
        banda3.setText("1x10^4");
        multiplicadora = "10000";
    }//GEN-LAST:event_amarillo3ActionPerformed

    private void naranja3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naranja3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(255,102,0));
        banda3.setText("1x10^3");
        multiplicadora = "1000";
    }//GEN-LAST:event_naranja3ActionPerformed

    private void blanco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blanco3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(255,255,255));
        banda3.setText("1x10^9");
        multiplicadora = "1000000000";
    }//GEN-LAST:event_blanco3ActionPerformed

    private void azul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azul3ActionPerformed
        // TODO add your handling code here:
        colorbanda3.setBackground(new java.awt.Color(0,0,204));
        banda3.setText("1x10^6");
        multiplicadora = "1000000";
    }//GEN-LAST:event_azul3ActionPerformed

    private void doradotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doradotoActionPerformed
        // TODO add your handling code here:
        colorbanda4.setBackground(new java.awt.Color(204,203,25));
        tolerancia.setText("5%");
    }//GEN-LAST:event_doradotoActionPerformed

    private void transpatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transpatoActionPerformed
        // TODO add your handling code here:
        colorbanda4.setBackground(new java.awt.Color(255,255,255));
        tolerancia.setText("20%");
    }//GEN-LAST:event_transpatoActionPerformed

    private void plateadotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateadotoActionPerformed
        // TODO add your handling code here:
        colorbanda4.setBackground(new java.awt.Color(204,204,204));
        tolerancia.setText("10%");
    }//GEN-LAST:event_plateadotoActionPerformed

    private void rojotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojotoActionPerformed
        // TODO add your handling code here:
        colorbanda4.setBackground(new java.awt.Color(255,51,0));
        tolerancia.setText("2%");
    }//GEN-LAST:event_rojotoActionPerformed

    private void cafetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafetoActionPerformed
        // TODO add your handling code here:
        colorbanda4.setBackground(new java.awt.Color(102,51,0));
        tolerancia.setText("1%");
    }//GEN-LAST:event_cafetoActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
        banda1.setText("");
        banda2.setText("");
        banda3.setText("");
        tolerancia.setText("");
        resultado.setText("");
        colorbanda1.setBackground(new java.awt.Color(255,255,255));
        colorbanda2.setBackground(new java.awt.Color(255,255,255));
        colorbanda3.setBackground(new java.awt.Color(255,255,255));
        colorbanda4.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_reiniciarActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        contenido = Double.parseDouble(banda1.getText() + banda2.getText());
        multiplicador = Double.parseDouble(multiplicadora);
        if (banda1.getText().equals("")||banda2.getText().equals("")||banda3.getText().equals("")||tolerancia.getText().equals(""))
        {
            resultado.setText("ERROR, LLENE TODOS LOS DATOS PARA CALCULAR EL VALOR DE SU RESISTENCIA");
        }
        else{
        if (banda1.getText().equals("0"))
        {
            contenido = Double.parseDouble(banda2.getText())/10;
        }
        calculo = contenido * multiplicador;
        if (calculo >= 1000000)
        {
            resultado.setText( calculo/1000000 + "MΩ" + " ± " + tolerancia.getText());
        }
        else if (calculo >= 1000)
        {
            resultado.setText( calculo/1000 + "KΩ" + " ± " + tolerancia.getText());
        }
        else
        {
        resultado.setText( calculo + "Ω" + " ± " + tolerancia.getText());
        }
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        Maininterfaz abrir = new Maininterfaz();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resistencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton amarillo1;
    private javax.swing.JButton amarillo2;
    private javax.swing.JButton amarillo3;
    private javax.swing.JButton azul1;
    private javax.swing.JButton azul2;
    private javax.swing.JButton azul3;
    private javax.swing.JTextPane banda1;
    private javax.swing.JTextPane banda2;
    private javax.swing.JTextPane banda3;
    private javax.swing.JButton blanco1;
    private javax.swing.JButton blanco2;
    private javax.swing.JButton blanco3;
    private javax.swing.JButton cafe1;
    private javax.swing.JButton cafe2;
    private javax.swing.JButton cafe3;
    private javax.swing.JButton cafeto;
    private javax.swing.JButton calcular;
    private javax.swing.JButton colorbanda1;
    private javax.swing.JButton colorbanda2;
    private javax.swing.JButton colorbanda3;
    private javax.swing.JButton colorbanda4;
    private javax.swing.JButton doradoto;
    private javax.swing.JButton gris1;
    private javax.swing.JButton gris2;
    private javax.swing.JButton gris3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton naranja1;
    private javax.swing.JButton naranja2;
    private javax.swing.JButton naranja3;
    private javax.swing.JButton negro1;
    private javax.swing.JButton negro2;
    private javax.swing.JButton negro3;
    private javax.swing.JButton plateadoto;
    private javax.swing.JButton reiniciar;
    private javax.swing.JTextPane resultado;
    private javax.swing.JButton rojo1;
    private javax.swing.JButton rojo2;
    private javax.swing.JButton rojo3;
    private javax.swing.JButton rojoto;
    private javax.swing.JTextPane tolerancia;
    private javax.swing.JButton transpato;
    private javax.swing.JButton verde1;
    private javax.swing.JButton verde2;
    private javax.swing.JButton verde3;
    private javax.swing.JButton violeta1;
    private javax.swing.JButton violeta2;
    private javax.swing.JButton violeta3;
    // End of variables declaration//GEN-END:variables
}
